---
- name: Create user on all machines
  user:
    name: "{{hive_user}}"
    comment: "spark superuser"
    group: "{{hadoop_group}}"
    groups: sudo
    home: "{{ hive_user_home }}"
    createhome: yes
    shell: /bin/bash
  register: created_user

- name: update ~/.bashrc
  template:
    src: bashrc.j2
    dest: "{{ hive_user_home }}/.bashrc"
  when: inventory_hostname in hive_hosts
