---
- name: Configure flink-env.sh
  template:
    src: flink-env.sh.j2
    dest: "{{flink_conf_dir}}/flink-env.sh"
    owner: "{{flink_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - flink-env
    - flink-log4j-config
  when: inventory_hostname in flink_hosts

# - name: Configure log4j.properties
#   template:
#     src: log4j.properties.j2
#     dest: "{{flink_conf_dir}}/log4j.properties"
#     owner: "{{flink_user}}"
#     group: "{{hadoop_group}}"
#     mode: 0755
#   tags:
#     - flink-log4j-config
#   when: inventory_hostname in flink_hosts

