---
# - name: Create user on all machines
#   user:
#     name: "{{kudu_user}}"
#     comment: "kudu superuser"
#     group: "{{hadoop_group}}"
#     groups: sudo
#     home: "{{ kudu_user_home }}"
#     createhome: yes
#     shell: /bin/bash
#   register: created_user

# - name: update ~/.bashrc
#   template:
#     src: bashrc.j2
#     dest: "{{ kudu_user_home }}/.bashrc"

- name: Delete user on all machines
  user:
    name: "{{kudu_user}}"
    state: absent
    remove: yes
