---
- name: Create rack awareness script
  template:
    src: rack-topology.sh.j2
    dest: "{{hadoop_rack_script_path}}"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  when: hadoop_rackaware is defined

- name: Create rack awareness data
  template:
    src: rack-topology.data.j2
    dest: "{{hadoop_conf_dir}}/rack-topology.data"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  when: hadoop_rackaware is defined

- name: Configure hadoop-env.sh
  template:
    src: hadoop-env.sh.j2
    dest: "{{hadoop_conf_dir}}/hadoop-env.sh"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart zkfc
  tags:
    - hdfs-env
    - hdfs-log4j-config

- name: Configure core-site.xml
  template:
    src: core-site.xml.j2
    dest: "{{hadoop_conf_dir}}/core-site.xml"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart zkfc
  tags:
    - hdfs-core-config

- name: Configure hdfs-site.xml
  template:
    src: hdfs-site.xml.j2
    dest: "{{hadoop_conf_dir}}/hdfs-site.xml"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart zkfc
  tags:
    - hdfs-site-config

- name: Configure log4j.properties
  template:
    src: log4j.properties.j2
    dest: "{{hadoop_conf_dir}}/log4j.properties"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart zkfc
  tags:
    - hdfs-log4j-config

- name: Download spark_shuffle lib to {{spark_shuffle_download_url}}
  get_url:
    url: "{{spark_shuffle_download_url}}"
    dest: "{{hadoop_install_dir}}/share/hadoop/yarn/lib/{{spark_shuffle_jar_file_name}}"
    validate_certs: no
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - yarn-site-config
    - spark-shuffle

- name: Configure yarn-site.xml
  template:
    src: yarn-site.xml.j2
    dest: "{{hadoop_conf_dir}}/yarn-site.xml"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart yarn-resourcemanager
    - Restart yarn-nodemanager
    - Restart zkfc
  tags:
    - yarn-site-config

- name: Configure mapred-site.xml
  template:
    src: mapred-site.xml.j2
    dest: "{{hadoop_conf_dir}}/mapred-site.xml"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  notify:
    - Restart namenode
    - Restart datanode
    - Restart journalnode
    - Restart yarn-resourcemanager
    - Restart yarn-nodemanager
    - Restart zkfc
  tags:
    - mapred-site-config

- name: Restart yarn-nodemanager
  service: name=yarn-nodemanager state=restarted
  tags:
    - yarn-site-config

- name: Restart yarn-resourcemanager
  service: name=yarn-resourcemanager state=restarted
  tags:
    - yarn-site-config