---
- name: Create datanode directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: "{{ hadoop_dfs_datanode_data_dir_perm }}"
  with_items: "{{ hadoop_datanode_dir_list }}"

- name: Set program variable to 'datanode'
  set_fact: program="datanode"

- name: Deploy systemd service for datanode
  template:
    src: hdfs.service.j2
    dest: /lib/systemd/system/hdfs-datanode.service
    owner: root
    group: root
    mode: 0644
  register: datanode_systemd_unit_altered

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  tags:
    - skip_ansible_lint

- name: Register datanode service
  service:
    name: hdfs-datanode
    enabled: yes
