---
- name: Create journalnode edits dir
  file:
    path: "{{hadoop_dfs_journalnode_edits_dir}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: "{{ hadoop_dfs_journalnode_edits_dir_perm }}"

- name: Set program variable to 'journalnode'
  set_fact: program="journalnode"

- name: Deploy systemd service for journalnode
  template:
    src: hdfs.service.j2
    dest: /lib/systemd/system/hdfs-journalnode.service
    owner: root
    group: root
    mode: 0644

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  tags:
    - skip_ansible_lint

- name: Register journalnode service
  service:
    name: hdfs-journalnode
    enabled: yes