---
- name: Configure mapred-site.xml
  template:
    src: mapred-site.xml.j2
    dest: "{{hadoop_conf_dir}}/mapred-site.xml"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"

- name: Configure workers
  template:
    src: workers.j2
    dest: "{{hadoop_conf_dir}}//workers"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0744

- name: Create namenode directories
  file:
    path: "{{item}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0700
  with_items: "{{ hadoop_namenode_dir_list }}"

- name: Create exclude file
  template:
    src: dfs.hosts.exclude.j2
    dest: "{{hadoop_conf_dir}}/dfs.hosts.exclude"
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0700
  notify: Restart namenode

- name: Set program variable to 'namenode'
  set_fact: program="namenode"

- name: Deploy systemd service for namenode
  template:
    src: hdfs.service.j2
    dest: /lib/systemd/system/hdfs-namenode.service
    owner: root
    group: root
    mode: 0644
  register: namenode_systemd_unit_altered

- name: Set program variable to 'zkfc'
  set_fact: program="zkfc"
  when: hadoop_ha_enabled

- name: Deploy systemd service for zkfc
  template:
    src: hdfs.service.j2
    dest: /lib/systemd/system/hdfs-zkfc.service
    owner: root
    group: root
    mode: 0644

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  tags:
    - skip_ansible_lint

- name: Register namenode service
  service:
    name: hdfs-namenode
    enabled: yes

- name: Register zkfc service
  service:
    name: hdfs-zkfc
    enabled: yes
  when: hadoop_ha_enabled