---
- name: Set program variable to 'secondarynamenode'
  set_fact: program="secondarynamenode"

- name: Create directories for namenode checkpoints
  file:
    path: "{{item}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0700
  with_items: "{{ hadoop_namenode_checkpoint_dir_list }}"

- name: Deploy systemd service for secondarynamenode
  template:
    src: hdfs.service.j2
    dest: /lib/systemd/system/hdfs-secondarynamenode.service
    owner: root
    group: root
    mode: 0644
  register: secondarynamenode_systemd_unit_altered

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: secondarynamenode_systemd_unit_altered.changed
  tags:
    - skip_ansible_lint

- name: Register secondarynamenode service
  service:
    name: hdfs-secondarynamenode
    enabled: yes
