---
- name: Create nodemanager local directories
  file:
    path: "{{hadoop_nodemanager_local_dir}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755

- name: Create nodemanager log directories
  file:
    path: "{{hadoop_nodemanager_log_dir}}"
    state: directory
    owner: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    mode: 0755

- name: Set program variable to 'resourcemanager'
  set_fact: program="resourcemanager"

- name: Deploy systemd service for resourcemanager
  template:
    src: yarn.service.j2
    dest: /lib/systemd/system/yarn-resourcemanager.service
    owner: root
    group: root
    mode: 0644

- name: Set program variable to 'nodemanager'
  set_fact: program="nodemanager"

- name: Deploy systemd service for nodemanager
  template:
    src: yarn.service.j2
    dest: /lib/systemd/system/yarn-nodemanager.service
    owner: root
    group: root
    mode: 0644

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  tags:
    - skip_ansible_lint

- name: Register resourcemanager service
  service:
    name: yarn-resourcemanager
    enabled: yes

- name: Register nodemanager service
  service:
    name: yarn-nodemanager
    enabled: yes