- name: Start spark-history-server
  service:
    name: spark-history-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop spark-history-server
  service:
    name: spark-history-server
    state: stopped
    enabled: no

- name: Restart spark-history-server
  service:
    name: spark-history-server
    state: restarted
    enabled: yes