- name: Start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop elasticsearch
  service:
    name: elasticsearch
    state: stopped
    enabled: no

- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
