---
## hbase's configuration will define here.
hbase_hosts: "{{ groups.hbase_nodes }}"
hbase_user_home: "/home/{{hbase_user}}"
hbase_install_dir: "{{ datalandfill_root_dir }}/hbase"
hbase_conf_dir: "{{hbase_install_dir}}/conf"
hbase_bin_dir: "{{hbase_install_dir}}/bin"
hbase_log_dir: /var/log/hbase
hbase_tmp_dir: /tmp/hbase
hbase_authenticate: True
hbase_user: hbase
hbase_download_url: "{{datalandfill_repo_url}}/hbase/{{hbase_version}}/hbase-{{hbase_version}}-bin.tar.gz"


hbase_ssh_fence: True
hbase_ssh_known_hosts_file: "{{ hbase_user_home }}/.ssh/known_hosts"
hbase_redistribute_ssh_keys: True


hbase_site_config: {}
hbase_site_config_defaults:
  hbase.rootdir: "hdfs://{{hadoop_cluster_name}}/user/hbase"
  hbase.master.port: 16000
  hbase.master.info.port: 16010
  hbase.master.ipc.address: 0.0.0.0
  hbase.cluster.distributed: true
  hbase.replication: true
  hbase.regionserver.info.port: 16030
  hbase.regionserver.handler.count: 30
  hbase.regionserver.metahandler.count: 10
  zookeeper.znode.parent: /hbase
  zookeeper.znode.rootserver: root-region-server
  hbase.zookeeper.quorum: "{{ groups['zookeeper_node'] | join(',') }}"
  hbase.zookeeper.property.clientPort: "{{zookeeper_client_port}}"
  hbase.wal.provider: filesystem
  replication.source.ratio: 1.0
  replication.source.nb.capacity: 1000
  hbase.client.write.buffer: 2097152
  hbase.client.pause: 100
  hbase.client.retries.number: 10
  hbase.client.scanner.caching: 100
  hbase.client.keyvalue.maxsize: 10485760
  hbase.ipc.client.allowsInterrupt: true
  hbase.client.primaryCallTimeout.get: 10
  hbase.client.primaryCallTimeout.multiget: 10
  hbase.master.handler.count: 25
  hbase.master.executor.openregion.threads: 5
  hbase.master.executor.closeregion.threads: 5
  hbase.splitlog.manager.timeout: 120000
  hbase.master.logcleaner.ttl: 60000
  hbase.server.thread.wakefrequency: 10000
  hbase.coprocessor.abortonerror: false
  hbase.superuser: hbase,hive,spark,hdfs,admin
  hbase.rpc.timeout: 60000
  hbase.snapshot.enabled: true
  hbase.snapshot.region.timeout: 300000
  hbase.snapshot.master.timeout.millis: 300000
  hbase.security.authentication: simple
  hbase.security.authorization: false
  hbase.row.level.authorization: false
  hbase.security.access.early_out: true
  hbase.rpc.protection: authentication
  zookeeper.session.timeout: 60000

  