---
- name: Configure spark-env.sh
  template:
    src: spark-env.sh.j2
    dest: "{{spark_conf_dir}}/spark-env.sh"
    owner: "{{spark_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - spark-env
    - spark-log4j-config
  when: inventory_hostname in spark_hosts

- name: Configure spark-defaults-conf
  template:
    src: spark-defaults.conf.j2
    dest: "{{spark_conf_dir}}/spark-defaults.conf"
    owner: "{{spark_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - spark-config
  when: inventory_hostname in spark_hosts


- name: Configure log4j.properties
  template:
    src: log4j.properties.j2
    dest: "{{spark_conf_dir}}/log4j.properties"
    owner: "{{spark_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - spark-log4j-config
  when: inventory_hostname in spark_hosts

- name: Configure hive-site.xml
  template:
    src: hive-site.xml.j2
    dest: "{{spark_conf_dir}}/hive-site.xml"
    owner: "{{spark_user}}"
    group: "{{hadoop_group}}"
    mode: 0755
  tags:
    - spark-config
  when: inventory_hostname in spark_hosts

- name: Set program variable to 'spark-history-server'
  set_fact:
    program: "spark-history-server"
  when: inventory_hostname in spark_history_server

- name: Deploy systemd service for spark-history-server
  template:
    src: spark-history-server.service.j2
    dest: /lib/systemd/system/spark-history-server.service
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in spark_history_server

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  tags:
    - skip_ansible_lint
  when: inventory_hostname in spark_history_server

- name: Register spark-history-server service
  service:
    name: spark-history-server
    enabled: yes
  when: inventory_hostname in spark_history_server

- name: Restart spark-history-server
  service:
    name: spark-history-server
    state: restarted
    enabled: yes
  when: inventory_hostname in spark_history_server