---
- name: Create user on all machines
  user:
    name: "{{spark_user}}"
    comment: "spark superuser"
    group: "{{hadoop_group}}"
    groups: sudo
    home: "{{ spark_user_home }}"
    createhome: yes
    shell: /bin/bash
  register: created_user

- name: update ~/.bashrc
  template:
    src: bashrc.j2
    dest: "{{ spark_user_home }}/.bashrc"
  when: inventory_hostname in spark_hosts
