---

- name: Copy Elasticsearch Config File
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_conf_file }}"
    mode: "660"
    owner: root
    group: "{{ es_group }}"
    force: yes
  notify: Restart elasticsearch
  tags:
    - elasticsearch

- name: Copy JVM Options Config File
  template:
    src: jvm.options.j2
    dest: "{{ es_jvm_file }}"
    owner: root
    group: "{{ es_group }}"
    mode: "660"
    force: yes
  notify: Restart elasticsearch
  tags:
    - elasticsearch

- name: Set Permissions For Elasticsearch Config Dir {{ es_conf_dir }}
  file:
    path: "{{ es_data_dirs }}"
    owner: root
    group: "{{ es_group }}"
    state: directory
    mode: "0775"
    recurse: yes
  tags:
    - elasticsearch

- name: Make Elasticsearch Service Is Started
  service: 
    name: elasticsearch
    state: started
    enabled: yes
  when: es_start_service
  tags:
    - elasticsearch